[net]
	[net.local]
	party_id   = 1
	ip         = "10.0.0.32"
	portrange  = "5000:6000"

	[net.extern]
	party_id  = 0
	ip        = "168.62.167.8"
	portrange = "6000:7000"

	[net.ti]
	ip   = "127.0.0.1"
	port = 4000

[sys]
	[sys.threads]
	optimise = false
	offline = 96
	online = 96

[numbersystem]
precision_frac = 10
precision_int  = 52

[correlatedrandomness]
debug = true							   #true doesn't interact with TI

[ml]
phase = "learning"                      #or, "inference"
model = "randomforest"           

	[ml.naivebayes]
	learning_cfg = "cfg/ml/naivebayes/learning1.toml"
	inference_cfg = "cfg/ml/naivebayes/inference1.toml"

	[ml.logisticregression]
	learning_cfg = "cfg/ml/logisticregression/learning1.toml"
	inference_cfg = "cfg/ml/logisticregression/inference1.toml"

	[ml.extratrees]
	learning_cfg = "cfg/ml/extratrees/learning1.toml"
	inference_cfg = "cfg/ml/extratrees/inference1.toml"

	[ml.randomforest]
	learning_cfg = "cfg/ml/randomforest/learning1.toml"
	inference_cfg = "cfg/ml/randomforest/inference1.toml"