[net]
	[net.local]
	party_id   = 1
	ip         = "10.0.0.32"
	portrange  = "5000:6000"

	[net.extern]
	party_id  = 0
	ip        = "168.62.167.8"
	portrange = "6000:7000"

	[net.ti]
	ip   = "127.0.0.1"
	port = 4000

[sys]
	[sys.threads]
	optimise = false
	offline = 48
	online = 24
	

[numbersystem]
precision_frac = 10
precision_int  = 52

[correlatedrandomness]
debug = true							   #true doesn't interact with TI

[ml]
phase = "inference"                      
model = "time_test"           

	[ml.naivebayes]
	learning_cfg = "cfg/ml/naivebayes/learning0.toml"
	inference_cfg = "cfg/ml/naivebayes/inference0.toml"

	[ml.logisticregression]
	learning_cfg = "cfg/ml/logisticregression/learning0.toml"
	inference_cfg = "cfg/ml/logisticregression/inference0.toml"

	[ml.extratrees]
	learning_cfg = "cfg/ml/extratrees/learning0.toml"
	inference_cfg = "cfg/ml/extratrees/inference0.toml"

	[ml.time_test]
	learning_cfg = "cfg/ml/time_test/learning0.toml"
	inference_cfg = "cfg/ml/time_test/inference0.toml"

	[ml.randomforest]
	learning_cfg = "cfg/ml/randomforest/learning0.toml"
	inference_cfg = "cfg/ml/randomforest/inference0.toml"