class_label_count = 2
attribute_count = 30
instance_count = 455
tree_count = 10
max_depth = 3
feature_count = 5
attr_value_count = 5
instance_selected_count = 455
epsilon = 0.05
data = "data/Party1_breast/1X_train.csv"
classes = "data/Party1_breast/1y_train.csv"
save_location = "treedata/Party1_trees.json"