class_label_count = 2
attribute_count = 30
instance_count = 455
tree_count = 5
max_depth = 2
feature_count = 5
epsilon = 0.01
data = "data/Party1_breast/1X_train.csv"
classes = "data/Party1_breast/1y_train.csv"
save_location = "treedata/Party1_trees.json"