class_label_count = 2
attribute_count = 30
instance_count = 455
tree_count = 3
max_depth = 4
feature_count = 10
epsilon = 0.05
data = "data/Party0_breast/1X_train.csv"
classes= "data/Party0_breast/1y_train.csv"
save_location = "treedata/Party0_trees.json"
